# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseTerraform@0
  inputs:
    terraformVersion: 'latest'

- script: |
    terraform init
    terraform plan
    terraform apply -auto-approve
  displayName: 'Run Terraform'

